//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lazyloadingtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationEntity
    {
        public ApplicationEntity()
        {
            this.Login = new HashSet<LoginEntity>();
        }
    
        public int ApplicationId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<LoginEntity> Login { get; set; }
    }
}
