//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lazyloadingtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizationEntity
    {
        public int AuthorizationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> NewUser { get; set; }
        public Nullable<bool> UpdateUser { get; set; }
        public Nullable<bool> DeleteUser { get; set; }
        public Nullable<bool> NewBaret { get; set; }
        public Nullable<bool> UpdateBaret { get; set; }
        public Nullable<bool> DeleteBaret { get; set; }
    
        public virtual UserEntity User { get; set; }
    }
}
