//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lazyloadingtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionEntity
    {
        public ConnectionEntity()
        {
            this.User = new HashSet<UserEntity>();
        }
    
        public int ConnectionId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string ServerName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Catalog { get; set; }
    
        public virtual CustomerEntity Customer { get; set; }
        public virtual ICollection<UserEntity> User { get; set; }
    }
}
