//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lazyloadingtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginEntity
    {
        public int LoginId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    
        public virtual ApplicationEntity Application { get; set; }
        public virtual UserEntity User { get; set; }
    }
}
