//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lazyloadingtest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AkilliBaretCmsEntities : DbContext
    {
        public AkilliBaretCmsEntities()
            : base("name=AkilliBaretCmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationEntity> ApplicationEntity { get; set; }
        public DbSet<AuthorizationEntity> AuthorizationEntity { get; set; }
        public DbSet<CityEntity> CityEntity { get; set; }
        public DbSet<ConnectionEntity> ConnectionEntity { get; set; }
        public DbSet<CustomerEntity> CustomerEntity { get; set; }
        public DbSet<LoginEntity> LoginEntity { get; set; }
        public DbSet<UserEntity> UserEntity { get; set; }
    }
}
