//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lazyloadingtest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntity
    {
        public UserEntity()
        {
            this.Authorization = new HashSet<AuthorizationEntity>();
            this.Login = new HashSet<LoginEntity>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ConnectionId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<AuthorizationEntity> Authorization { get; set; }
        public virtual ConnectionEntity Connection { get; set; }
        public virtual CustomerEntity Customer { get; set; }
        public virtual ICollection<LoginEntity> Login { get; set; }
    }
}
